# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    jsonData:
      version: Flux
      organization: none
      defaultBucket: bucket
      tlsSkipVerify: true
    secureJsonData:
      token: mytoken