# Zigbee2MQTT Configuration - House Location
# This file will be managed by Git and deployed via Git Pull add-on

version: 4

# MQTT integration (managed by Home Assistant add-on)
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: !secret mqtt_password

# Coordinator settings
serial:
  port: /dev/ttyACM0
  adapter: ember
  baudrate: 115200
  rtscts: false

# Advanced settings with network configuration
advanced:
  log_level: info
  channel: 15
  network_key: !secret zigbee_network_key
  pan_id: !secret zigbee_pan_id
  ext_pan_id: !secret zigbee_ext_pan_id

# Frontend
frontend:
  enabled: true
  port: 8099

# Home Assistant integration
homeassistant:
  enabled: true

# Device configurations (Git-managed friendly names)
devices:
  '0x54ef441000edf7c1':
    friendly_name: 'Food Storage Sensor'
    retain: false
    description: 'Kitchen food storage temperature and humidity sensor'
  '0xb4e3f9fffea76436':
    friendly_name: 'Living Room Light'
    retain: false  
    description: 'Main living room light bulb'

# Groups (for Zigbee groups if needed)
groups: {}
