version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/home-assistant:/config
    restart: unless-stopped
    privileged: true
    network_mode: host