version: '3'
services:
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:latest
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - ~/homebridge:/homebridge