version: '3'
services:
  telegraf:
    container_name: telegraf
    image: telegraf:latest
    depends_on:
      - influxdb
    network_mode: host
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/monitoring/telegraf:/etc/telegraf/:ro
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    network_mode: host
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/monitoring/influx/influx-data:/var/lib/influxdb2
  influxdb_cli:
    container_name: influxdb-cli
    image: influxdb:latest
    env_file: ~/monitoring/configuration.env
    depends_on:
      - influxdb
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    volumes:
      # Mount for influxdb data directory and configuration
      - ~/monitoring/influx/influx-data:/var/lib/influxdb2
      # - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:rw
      # - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:rw
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    env_file: ~/monitoring/configuration.env
    network_mode: host
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - grafana-data:/var/lib/grafana
      - ~/monitoring/grafana/dashboards:/var/lib/grafana/dashboards/
      - ~/monitoring/grafana/plugins:/var/lib/grafana/plugins
      - ~/monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ~/monitoring/grafana/log:/var/log/grafana
volumes:
  grafana-data:
  influx-data:
