version: '3'
services:
  telegraf:
    container_name: telegraf
    image: telegraf:latest
    depends_on:
      - influxdb
    network_mode: host
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/compose-volumes/monitoring/telegraf:/etc/telegraf/:ro
  influxdb:
    container_name: influxdb
    image: influxdb:1.8-alpine
    network_mode: host
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/compose-volumes/monitoring/influx/config/influxdb.conf:/etc/influxdb/influxdb.conf
      - ~/compose-volumes/monitoring/influx/influx-data:/var/lib/influxdb
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    env_file: ~/compose-volumes/monitoring/configuration.env
    network_mode: host
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - grafana-data:/var/lib/grafana
      - ~/compose-volumes/monitoring/grafana/dashboards:/var/lib/grafana/dashboards/
      - ~/compose-volumes/monitoring/grafana/plugins:/var/lib/grafana/plugins
      - ~/compose-volumes/monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ~/compose-volumes/monitoring/grafana/log:/var/log/grafana
volumes:
  grafana-data: {}