version: "3"
services:
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/mqtt/conf:/mosquitto/conf
      - ~/mqtt/data:/mosquitto/data
      - ~/mqtt/log:/mosquitto/log
