version: "3"
services:
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    network_mode: host
    privileged: true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/compose-volumes/mqtt/conf:/mosquitto/config
      - ~/compose-volumes/mqtt/data:/mosquitto/data
      - ~/compose-volumes/mqtt/log:/mosquitto/log
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    depends_on:
      - mosquitto
    network_mode: host
    privileged: true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/compose-volumes/zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:latest
    depends_on:
      - mosquitto
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - ~/compose-volumes/homebridge:/homebridge    
