# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  # Name of the location where Home Assistant is running
  name: "Summer Residence"
  # Location required to calculate the time the sun rises and sets
  latitude: 49.901263
  longitude: 14.340764
  # 'metric' for Metric, 'us_customary' for US Customary
  unit_system: metric
  # Pick yours from here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: "Europe/Prague"
  configs: !include_dir_named configs/