#define WIFI_SSID "SSID here"
#define WIFI_PASSWORD "WLAN AP password here"
#define MMQT_SERVER "hivemq.cloud server URL here"
#define MMQT_USERNAME "hivemq.cloud server URL here"
#define MMQT_PASSWORD "hivemq.cloud server URL here"