version: "3"
services:
  setup:
    build: .
    container_name: setup
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /git/compose-volumes:~/central-server/initial-config/
      - /git/docker-compose:~/central-server/docker-compose