# EV Dynamic Load Balancing
# Dynamically adjusts EV charging to prevent grid overload based on real-time consumption
# No cloud dependency - works fully offline via local MQTT
#
# Installation: 3×32A (22kW grid capacity)
# Logic: Monitors actual household power (updates every ~1s), reduces charging when consumption increases
#        CRITICAL: go-eController household reading INCLUDES charger consumption - must subtract current 
#        charger draw before calculating available power (otherwise charger counts against itself)
# Reserve: Safety buffer for sudden spikes (kettle, oven, etc.)
# MQTT: go-eCharger/600187/amp/set

# Template sensor for continuous calculation (works even without car connected)
template:
  - sensor:
      - name: "EV Available Charging Current"
        unique_id: ev_available_charging_current
        unit_of_measurement: "A"
        device_class: current
        state_class: measurement
        state: >
          {% set grid_capacity = 22000 %}
          {% set household_total = states('sensor.go_econtroller_917809_home_power') | float(0) %}
          {% set reserve = states('input_number.ev_household_reserve_watts') | float(3000) %}
          {% set charger_current_draw = states('sensor.go_echarger_600187_power_total') | float(0) %}
          {% set household_excluding_charger = [0, household_total - charger_current_draw] | max | float %}
          {% set available = [0, grid_capacity - household_excluding_charger - reserve] | max | float %}
          {% set target_raw = (available / 690) | round(0, 'floor') %}
          {{ 0 if target_raw < 6 else [target_raw, 16] | min | int }}
        availability: "{{ has_value('sensor.go_econtroller_917809_home_power') }}"
        attributes:
          household_power: "{{ states('sensor.go_econtroller_917809_home_power') | float(0) | round(1) }}"
          charger_power: "{{ states('sensor.go_echarger_600187_power_total') | float(0) | round(1) }}"
          household_excluding_charger: "{{ ([0, states('sensor.go_econtroller_917809_home_power') | float(0) - states('sensor.go_echarger_600187_power_total') | float(0)] | max) | round(1) }}"
          available_power: "{{ ([0, 22000 - ([0, states('sensor.go_econtroller_917809_home_power') | float(0) - states('sensor.go_echarger_600187_power_total') | float(0)] | max) - states('input_number.ev_household_reserve_watts') | float(3000)] | max) | round(1) }}"
          reserve_watts: "{{ states('input_number.ev_household_reserve_watts') | float(3000) | round(0) }}"
          grid_capacity: 22000

input_number:
  ev_household_reserve_watts:
    name: "EV Charging - Household Reserve"
    min: 3000
    max: 10000
    step: 1000
    unit_of_measurement: "W"
    icon: mdi:home-lightning-bolt
    initial: 3000  # Safety buffer: kettle(2kW) + margin, adjustable up to 10kW

  ev_last_set_amps:
    name: "EV Last Set Amperage"
    min: 0
    max: 16
    step: 1
    unit_of_measurement: "A"
    mode: box

input_boolean:
  ev_dynamic_load_balancing_enabled:
    name: "EV Dynamic Load Balancing"
    icon: mdi:car-electric

automation:
  # Continuously sync actual charger amperage to track manual adjustments
  - id: 'ev_sync_charger_amperage_continuous'
    alias: "EV Sync Charger Amperage Continuously"
    description: "Keep ev_last_set_amps synchronized with actual charger setting (tracks manual adjustments)"
    mode: single
    triggers:
      - platform: homeassistant
        event: start
      # Track any change to actual charger amperage (manual adjustments, app changes, etc.)
      - platform: state
        entity_id: sensor.go_echarger_600187_allowed_charge_current
    conditions:
      - condition: template
        value_template: "{{ states('sensor.go_echarger_600187_allowed_charge_current') not in ['unknown', 'unavailable'] }}"
      # Only log if value actually changed (prevent spam)
      - condition: template
        value_template: "{{ states('sensor.go_echarger_600187_allowed_charge_current') | int != states('input_number.ev_last_set_amps') | int }}"
    actions:
      - service: input_number.set_value
        target:
          entity_id: input_number.ev_last_set_amps
        data:
          value: "{{ states('sensor.go_echarger_600187_allowed_charge_current') | int }}"
      - service: logbook.log
        data:
          name: "EV Load Balancing"
          message: "Synced charger amperage: {{ states('input_number.ev_last_set_amps') | int }}A → {{ states('sensor.go_echarger_600187_allowed_charge_current') }}A"

  - id: 'ev_dynamic_load_balancing'
    alias: "EV Dynamic Load Balancing"
    description: "Adjust charging to prevent grid overload"
    mode: single
    triggers:
      - platform: state
        entity_id: sensor.ev_available_charging_current
    conditions:
      - condition: state
        entity_id: input_boolean.ev_dynamic_load_balancing_enabled
        state: 'on'
      # Include WaitCar (ready to charge) and Complete (might resume) for pre-emptive safety
      - condition: template
        value_template: "{{ states('sensor.go_echarger_600187_car_state') in ['Charging', 'WaitCar', 'Complete'] }}"
      - condition: template
        value_template: "{{ states('sensor.ev_available_charging_current') not in ['unknown', 'unavailable'] }}"
    actions:
      - variables:
          current: "{{ states('input_number.ev_last_set_amps') | int(0) }}"
          target: "{{ states('sensor.ev_available_charging_current') | int(0) }}"
          diff: "{{ (target | int) - (current | int) }}"
      # Asymmetric hysteresis: instant decrease (safety), threshold for increase (prevent oscillation)
      - if:
          - condition: template
            value_template: "{{ diff < 0 or diff >= 1 }}"
        then:
          - service: input_number.set_value
            target:
              entity_id: input_number.ev_last_set_amps
            data:
              value: "{{ target }}"
          - service: mqtt.publish
            data:
              topic: "go-eCharger/600187/amp/set"
              payload: "{{ target }}"
          - service: logbook.log
            data:
              name: "EV Load Balancing"
              message: "Adjusted: House {{ state_attr('sensor.ev_available_charging_current', 'household_excluding_charger') | int }}W + Charger {{ state_attr('sensor.ev_available_charging_current', 'charger_power') | int }}W → {{ current }}A→{{ target }}A"

  # Sync charger power to controller for local tracking (no cloud required)
  # DISABLED: ccp array format not documented, causing MQTT spam without confirmed functionality
  # Re-enable after testing correct array index via HA Developer Tools → Services
  # Test payload: [null,null,5000,null...] or other index combinations
  # - id: 'ev_sync_charger_power_to_controller'
  #   alias: "EV Sync Charger Power to Controller"
  #   description: "Send charger power data to controller via MQTT for local car power tracking (ccp = car charging power)"
  #   mode: single
  #   triggers:
  #     - platform: state
  #       entity_id: sensor.go_echarger_600187_power_total
  #     - platform: homeassistant
  #       event: start
  #   conditions:
  #     - condition: template
  #       value_template: "{{ states('sensor.go_echarger_600187_power_total') not in ['unknown', 'unavailable'] }}"
  #     # Throttle: only sync if power changed by >100W or first sync after HA start
  #     - condition: template
  #       value_template: >
  #         {% set current = states('sensor.go_echarger_600187_power_total') | int(0) %}
  #         {% set last = state_attr('automation.ev_sync_charger_power_to_controller', 'last_triggered') %}
  #         {{ last is none or (current | int - trigger.from_state.state | int(0)) | abs > 100 }}
  #   actions:
  #     # go-eController ccp array format: [grid_power, home_power, car_power, ...nulls...]
  #     # We only set car_power (index 2), leave grid/home as null (controller calculates from CT clamps)
  #     # Topic: go-eController/917809/ccp/set (car charging power set)
  #     - service: mqtt.publish
  #       data:
  #         topic: "go-eController/917809/ccp/set"
  #         payload: >
  #           [null,null,{{ states('sensor.go_echarger_600187_power_total') | int }},null,null,null,null,null,null,null,null,null,null,null,null,null]